name: weconnect-server

services:
  weconnect-db:
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    image: postgres:16-alpine
    networks:
      - wevote
    user: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /tmp/docker:/tmp                 # Needed to get backup files into psql to test fastback

  weconnect-api:
    build:
      dockerfile: docker/Dockerfile.dev
      args:
        - HTTPS_SSL_HOST=${HOST}
    depends_on:
      weconnect-db:
        condition: service_healthy
    environment:
      - DATABASE_HOST=weconnect-db                # use db host/port for weconnect-db service (defined above)
      - DATABASE_PORT=5432
      - HTTPS_SSL_CERT=${HTTPS_SSL_CERT:-/etc/ssl/certs/cert.pem}    # use automatically created cert as a fallback
      - HTTPS_SSL_KEY=${HTTPS_SSL_KEY:-/etc/ssl/private/key.pem}     # use automatically created key as a fallback
    volumes:
      - .:/app
      # Prevent host node_modules from shadowing the container's installed node_modules
      - /app/node_modules
    networks:
      - wevote
    ports:
      - "0.0.0.0:4500:4500"   # access the WeConnect API at https://wevotedeveloper.com:4500
      - "127.0.0.1:5555:5555" # expose prisma studio running inside container
      - "0.0.0.0:9229:9229"   # The WebStorm Node debugger port

  pgadmin:
    image: dpage/pgadmin4:8.4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL:-fake_email@wevoteeducation.org}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD:-admin}
      DATABASE_USER: ${DATABASE_USER:-postgres}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-admin}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "8080:80"
    networks:
      - wevote


networks:
  wevote:
    name: wevote
    external: true

volumes:
  postgres_data:
  pgadmin_data:

