FROM public.ecr.aws/docker/library/node:22

# install postgresql-client for database health checks and debugging
RUN apt-get update && apt-get install -y postgresql-client && rm -rf /var/lib/apt/lists/*

ENV NODE_ENV=production
WORKDIR /app
COPY . .
COPY docker/scripts/entrypoint.js /app/entrypoint.js
RUN chmod +x /app/entrypoint.js
RUN npm install
USER node
ENV PORT=8000
EXPOSE 8000
ENTRYPOINT ["/app/entrypoint.js"]
CMD ["npm", "run", "prod"]

